basePath: /
definitions:
  domain.Contact:
    properties:
      email:
        type: string
      id:
        type: integer
      nama:
        type: string
      phone:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Simple phonebook API (Gin + PostgreSQL).
  title: Phonebook API
  version: "1.0"
paths:
  /contacts:
    get:
      description: Returns list of contacts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Contact'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all contacts
      tags:
      - contacts
swagger: "2.0"
